//
// Created by Sebastian on 22/11/2023.
//

#ifndef MODERN_CPP_EXERCISES_CPP23_001_OPTIONAL_PAR_IN_LAMBDAS_H
#define MODERN_CPP_EXERCISES_CPP23_001_OPTIONAL_PAR_IN_LAMBDAS_H

namespace cpp23::ex001 {
    void doit();
}

#endif //MODERN_CPP_EXERCISES_CPP23_001_OPTIONAL_PAR_IN_LAMBDAS_H
